### ISSUE TITLE
get blank subject 

### ISSUE THREAD

**Issue by richiverse** [eugene-eeo/mailthon#14]
Following the README and I receive an email but missing subject. I'm on Ubuntu 14.04 & python 3.4.

Also using google smtp and 2 factor pwd for authentication.

**Comment by eugene-eeo** [comment]
Hi, could you make sure that it happens like you said and provide me with the code you used (minus the password and auth) to send the email? In theory this shouldn't happen because there are tests in place to ensure that the Subject header is set, but we may have overlooked something.
