### ISSUE TITLE
Can't Send E-Mail Using Python 3

### ISSUE THREAD

**Issue by href** [eugene-eeo/mailthon#18]
E-Mail sending under Python 3 doesn't work for me. Even running the example code in the README fails with the following error:

```python
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    r = p.send(mail)
  File "virtualenv/python3.4/site-packages/mailthon/postman.py", line 91, in send
    return self.deliver(conn, envelope)
  File "virtualenv/python3.4/site-packages/mailthon/postman.py", line 81, in deliver
    envelope.string(),
  File "Python 3.4/lib/python3.4/smtplib.py", line 772, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "Python 3.4/lib/python3.4/smtplib.py", line 503, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "Python 3.4/lib/python3.4/smtplib.py", line 142, in quoteaddr
    displayname, addr = email.utils.parseaddr(addrstring)
  File "Python 3.4/lib/python3.4/email/utils.py", line 235, in parseaddr
    addrs = _AddressList(addr).addresslist
  File "Python 3.4/lib/python3.4/email/_parseaddr.py", line 500, in __init__
    self.addresslist = self.getaddrlist()
  File "Python 3.4/lib/python3.4/email/_parseaddr.py", line 253, in getaddrlist
    ad = self.getaddress()
  File "Python 3.4/lib/python3.4/email/_parseaddr.py", line 263, in getaddress
    self.gotonext()
  File "Python 3.4/lib/python3.4/email/_parseaddr.py", line 236, in gotonext
    if self.field[self.pos] in self.LWS + '\n\r':
TypeError: 'in <string>' requires string as left operand, not int
```

The problem lies in the `Postman` class, which encodes the addresses to byte before handing them off to Python's smtplib. Smtplib however seems to expect strings, not bytes. In Python 2.7 that doesn't really matter, but of course Python 3 is stricter about it.

In fact, using the following replacement for `Postman` works for me in Python 2.7 / Python 3.4:

```python
class FixedPostman(Postman):
    def deliver(self, conn, envelope):
        rejected = conn.sendmail(
            envelope.mail_from,
            envelope.receivers,
            envelope.string(),
        )

        return self.response_cls(conn.noop(), rejected)
````
To be honest though I only got it working. I haven't verified if this is the correct way of doing it.

From what I've seen the existing tests can't catch these kinds of errors, because the SMTP connection is mocked out. My guess is that using a "real" smtp server like the one in the following py.test plugin would show those errors with the existing test suite:

https://pypi.python.org/pypi/pytest-localserver

**Comment by eugene-eeo** [comment]
Would you want to write a PR to fix it? I am not having much time on my hand at the moment. Sorry that I haven't discovered this issue- it seems that most people are on Python 2 and I was using Python 2 when manually testing it against my own Gmail account periodically. We can of course rename the function to something like ``stringify_address`` and return ``str(res)`` in the ``encode_address`` function. What do you think?

**Comment by href** [comment]
I don't mind having a stab at it. But I lack time as well :)

However, I'll add it to my todo list. Once I have time I find the time I'll write a test/fix - I try to give back to the tools we use and from time to time I spend an an afternoon on whatever I have open.

For now it's at least a documented bug.

Your plan of action sounds good, so come the time I'll probably do it as you propose.

**Comment by eugene-eeo** [comment]
@href since your latest PR addresses this issue (`stringify_address`) I shall close this issue.

**Comment by href** [comment]
:+1:
