### ISSUE TITLE
New mailthon release

### ISSUE THREAD

**Issue by href** [eugene-eeo/mailthon#24]
If it's not too much trouble, may I ask for a release of mailthon with the latest changes?

Thanks!

**Comment by eugene-eeo** [comment]
Ok, sounds good. I will clean up the code base a little and push a release. Note that it *will* take some time, probably a day or two so don't get over excited :sweat_smile:

**Comment by psihonavt** [comment]
+1 for new release :)

**Comment by href** [comment]
Excellent, thanks!

**Comment by eugene-eeo** [comment]
@href, @psihonavt Is version 0.1.1 an appropriate one? On one hand, the helpers API have been changed but on the other hand it does not introduce any changes if you are only using the "exposed" APIs. Also I am having a separate 0.2 branch which breaks a lot of stuff.

**Comment by href** [comment]
Okay with me

**Comment by psihonavt** [comment]
Works for me also.

**Comment by eugene-eeo** [comment]
Ok, version `0.1.1` is out.

**Comment by href** [comment]
Thank you! Works great.
