### ISSUE TITLE
Exception raise when Header attr is "None", like: SUB

### ISSUE THREAD

**Issue by LiKevin** [eugene-eeo/mailthon#28]
[http://mailthon.readthedocs.io/en/latest/quickstart.html](url)

`from mailthon import email

envelope = email(
    sender='sender <username@mail.com>',
    receivers=['receiver@mail.com'],
    subject='Hello World!',
    content='Hi!',
)`

**Comment by eugene-eeo** [comment]
The ``email`` function assumes, rather sanely that all emails have a subject header. If I get enough requests about fixing this then I will change the code. If you really don't want to include a subject header then consider manually creating an Envelope object.
