### ISSUE TITLE
Anonymous email sending via SMTP is unsupported. 

### ISSUE THREAD

**Issue by LiKevin** [eugene-eeo/mailthon#29]
`
class Auth(Middleware):
    """
    Middleware implementing authentication via LOGIN.
    Most of the time this middleware needs to be placed
    *after* TLS.

    :param username: Username to login with.
    :param password: Password of the user.
    """

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def __call__(self, conn):
        if self.username and self.password:  #may be some actions like: simple check of the user/passwd inputs ...??
            conn.login(self.username,
                       self.password)`

**Comment by eugene-eeo** [comment]
If you dont want to use the LOGIN capability then just don't use the Auth middleware.
