### ISSUE TITLE
Encoding failure

### ISSUE THREAD

**Issue by rslinckx** [eugene-eeo/mailthon#7]
r = p.send(email(content=u'<p>Hello 世界</p>',subject=u'éHello world',sender=u'éJohn <john@jon.com>',receivers=[u'édoe@jon.com']))

This fails because the receivers are forced to ascii which can't represent the 'é', they should be quoted instead. Same with cc/bcc

**Comment by eugene-eeo** [comment]
Hi first of all thanks for reporting! This is a known issue and is currently a work in progress. Perhaps you would like to check out the [``internationalised-headers``](https://github.com/eugene-eeo/mailthon/tree/internalionalised-headers) branch and perhaps work on it as well?

**Comment by rslinckx** [comment]
Regarding the branch, I think it's better not to encode everything, but only the headers that are processed in some ways by the library: to, from, sender, subject. The Date is ascii and can be left as is, so is the msgid.

Regarding the To and CC headers, I think the values should be encoded separately and then joined with ","

Finally the unicode value passed as to/cc/bcc, which is used for the 'receivers' property is passed as unicode string to sendmail(), which fails. It should be encoded before being passed to sendmail. You can take a look at: https://github.com/mattupstate/flask-mail/blob/master/flask_mail.py#L102 for the encoding of email adresses

**Comment by eugene-eeo** [comment]
Not trying to strongly disapprove of your opinion, but the main advantage that we have with unicode headers is that it makes it much easier to write headers. Also, a nice feature of the ``email.header`` library is that the ``Header`` object decides whether or not something needs to be encoded. If the text is pure ASCII it is send as-is, to my understanding.

Regarding the unicode values passed to sendmail - I didn't test it against a real SMTP object, so thanks for letting me know of it! It seems tricky to fix. Does a simple ``encode`` solve your problem?

**Comment by eugene-eeo** [comment]
Ok, on Python 2.7.9 ``sendmail`` seems to be ok with unicode email addresses. On Python 3 it's alright anyways because everything is in unicode. Which version of Python are you on?

**Comment by rslinckx** [comment]
I'm using 2.7.8 at the moment, but i'm not sure there is a difference in smtplib.

I'm testing with the python debugging server:

    python -m smtpd -n -c DebuggingServer -d localhost:1025

You can reproduce using:

    from mailthon.postman import Postman
    from mailthon.api import email
    p = Postman(host='localhost', port=1025)
    e = email(content=u'<p>é</p>',subject=u'éHello world',sender=u'éJohn <john@jon.com>',receivers=[u'édoe@jon.com', 'édoe2@jon.com'])
    print e.string()
    r = p.send(e)

This fails with the UnicodeEncodeError, you can also see in the print that all headers are encoded (even date and msgid). Curiously in the master branch, the headers are correctly encoded

master:

    Content-Type: multipart/mixed; boundary="===============4282568036384866428=="
    MIME-Version: 1.0
    Sender: =?utf-8?b?w6lKb2huIDxqb2huQGpvbi5jb20+?=
    Cc:
    To: =?utf-8?b?w6lkb2VAam9uLmNvbQ==?=
    Date: Wed, 27 May 2015 12:19:41 +0200
    Message-ID: <20150527101941.93841.1500@arschlord-2.local>
    Subject: =?utf-8?q?=C3=A9Hello_world?=

internationalised-headers:

    Content-Type: multipart/mixed; boundary="===============8131507906615249899=="
    MIME-Version: 1.0
    Sender: =?utf-8?b?w6lKb2huIDxqb2huQGpvbi5jb20+?=
    Cc:
    To: =?utf-8?b?w6lkb2VAam9uLmNvbQ==?=
    Date: =?utf-8?q?Wed=2C_27_May_2015_12=3A23=3A49_+0200?=
    Message-ID: =?utf-8?q?=3C20150527102349=2E93921=2E25241=40arschlord-2=2Elocal=3E?=
    Subject: =?utf-8?q?=C3=A9Hello_world?=

(Also note that the CC header is present but empty)

**Comment by eugene-eeo** [comment]
CC being empty is known behaviour. This is because the headers passed to the Headers mapping are applied as is. Also it simplifies the code in the ``api.email`` function. Do you mean that in the master branch without using the ``email.header.Header`` class it works correctly?

**Comment by rslinckx** [comment]
In the master branch the headers seem correct, i don't know where they are encoded, but they are... Also the pure ascii headers are correctly preserved .

However the same problem with sendmail exists that the recipients are not encoded and it fails when rendering the 'RCPT TO %s' command

**Comment by eugene-eeo** [comment]
It seems that the email library already supports unicode headers. I am really confused right now. My Python is 2.7.9 but I'll test against 2.7.8 to see if it holds true.

```python
>>> from email.message import Message
>>> m = Message()
>>> m['Header'] = u'hi å'
>>> m.as_string()
'Header: =?utf-8?b?aGkgw6U=?=\n\n'
>>> m['Header']
u'hi \xe5'
```

**Comment by rslinckx** [comment]
I have the same results in python 2.7.8

**Comment by rslinckx** [comment]
So it would seem that headers are automatically encoded when given as unicode string. Now the only remaining problem is the sendmail() call which does not support unicode arguments :)

**Comment by eugene-eeo** [comment]
Nice. So I'll be deleting the branch since we technically don't need it any more. :smile:

Do you want to just throw in a few decodes in the headers and submit a PR? I'm not able to write code at the moment as I'm away from my computer.

**Comment by rslinckx** [comment]
I can take a look today or tomorrow

**Comment by eugene-eeo** [comment]
Alright, thanks! I really appreciate it. Have a :cake: too.

**Comment by eugene-eeo** [comment]
@rslinckx since this issue is fixed, should I close it?
