### ISSUE TITLE
Unable to specify an envelope sender other than From or Sender headers

### ISSUE THREAD

**Issue by rslinckx** [eugene-eeo/mailthon#8]

**Comment by eugene-eeo** [comment]
You can do it manually if you're using the OO interface rather than the main ``mailthon.api`` module. For example:

```python
from mailthon.envelope import Envelope
from mailthon.enclosure import PlainText

env = Envelope(
    headers={'Sender-Header': 'value'},
    enclosure=[
        PlainText('some-content'),
    ]
)
```

The reason being that most of the time users wouldn't want to inject their own headers. Feel free to make a pull request implementing your custom header "injection" feature though.

**Comment by rslinckx** [comment]
It's not a header, it's the value passed to connection.sendmail(sender, recipients, message) which is used in the smtp protocol as MAIL FROM xxxx

**Comment by eugene-eeo** [comment]
Oh I see. This is usually not expected behaviour and not what users expect though. If it answers your question, you can use ``Resent-*`` headers and mailthon will respect them. However if you are not looking for a non-headers based solution, would you want to write a pull request for that? :)

**Comment by rslinckx** [comment]
Yes it's not a very common usecase, but it should at least be possible. In my case, the MAIL FROM is a special address that will catch the bounces and smtp errors, the Sender will be the "public" email address of my webapp, and the From will be the user email adress (on which i have no control).

I think the simplest is to add a mail_from=None param to Envelope.__init__ which defaults to the current value if it's not set, and call connection.sendmail(envelope.mail_from, ....)

**Comment by eugene-eeo** [comment]
I've added this functionality in the [``extra-senders``](https://github.com/eugene-eeo/mailthon/tree/extra-senders) branch. Could you take a look at it and check that it does what you expect? A test is written but it's best to get feedback.

**Comment by rslinckx** [comment]
I think you should leave the old sender property as is, and add a new one, which is then used in the sendmail call. That way one can access either values easily

**Comment by eugene-eeo** [comment]
:+1: agreed.

**Comment by eugene-eeo** [comment]
After thinking about it for a while, I'm more inclined towards *not* including this in the library. This is because it's quite awkward- ``Envelope(mail_from='addr@mail.com', headers=[to('addr2@mail.com')])`` seems very unintuitive. Also backwards compatibility is an issue. What is your opinion on this issue?

I know you somehow need it for your application and I respect that, but is subclassing and extending a good enough solution? It reduces the "weight" on our side. Hope you understand.

**Comment by rslinckx** [comment]
Here's a pull request showing what i had in mind.

As you can see there can be a difference between the envelope sender and the message sender.

In real life you would write the envelope sender on the back of the envelope, and the 'real' sender inside the envelope on the mail itself
