### ISSUE TITLE
Header containing addresses should support the ('name', 'address') tuple convention

### ISSUE THREAD

**Issue by rslinckx** [eugene-eeo/mailthon#9]
It's sometimes easier and safer to let the library do the job of sanitizing and formatting those values correctly, especially when they come from untrusted sources (user-input data)

Normally email.utils.formataddr will do the job of properly escaping and formatting the string to be used as header which should then be quoted properly.

**Comment by eugene-eeo** [comment]
Firstly, I've considered this factor early on in development but it sort of slowed down my progress. Now that the API has sort of stabilised, would you like to write a PR that fixes/addresses this issue?

**Comment by eugene-eeo** [comment]
This is fixed in the 8855767 commit.

**Comment by rslinckx** [comment]
Thanks a lot !
